apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - target:
      kind: Subscription
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'tech-preview'
      - op: replace
        path: /spec/installPlanApproval
        value: Manual
