apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - target:
      kind: Subscription
      name: cluster-logging
      namespace: openshift-logging
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
