apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: csi-secrets-store
- kind: ServiceAccount
  name: secrets-provider-aws-secrets-store-csi-driver-provider-aws
  namespace: csi-secrets-store
