apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: seed-application
  name: secrets-provider-aws
  namespace: openshift-gitops
spec:
  destination:
    namespace: csi-secrets-store
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: secrets-store-csi-driver-provider-aws
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    targetRevision: 0.2.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
