---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../../base
  - test-secrets1/
patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: external-secrets-operator
