---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: Application
    name: cert-manager-operator
  patch: |-
    - op: replace
      path: /spec/source/path
      value: './manifests/cert-manager/overlays/prod'
- target:
    kind: Application
    name: openshift-logging
  patch: |-
    - op: replace
      path: /spec/source/path
      value: './manifests/openshift-logging/overlays/prod'
