apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: MySecret
      version: v1
      property: username
  - secretKey: password
    remoteRef:     
      key: MySecret
      version: v1  
      property: password
  dataFrom:
  - extract:
      key: MySecret
