---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: test-secrets1
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "10"
resources:
  - ns.yaml
  - sa.yaml
  - secretstore.yaml
  - externalsecret.yaml
